- name: install docker ce
  yum:
    disablerepo: "*"
    enablerepo: "kubernetes"
    name:
      - docker-ce
    state: present
  tags:
    - rpm
    - docker

- name: create docker setting dir
  file: name=/etc/docker state=directory owner=root group=root mode=0755
  tags:
    - docker

- name: setting docker daemon
  template: src=daemon.json.j2 dest=/etc/docker/daemon.json
  tags:
    - docker
  register: docker_config

- name: restart docker service
  service: name=docker state=restarted enabled=yes daemon_reload=yes
  tags:
    - docker
  when:
    docker_config.changed

- name: enable docker service
  service: name=docker state=started enabled=yes daemon_reload=yes
  tags:
    - docker